different approach for reporting jest results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,17 +20,18 @@ jobs:
       - run: npm i
       - run: npm run build --if-present
       - run: npm run ci-test
-  collect-test-report:
-    name: JEST Report
-    runs-on: ubuntu-latest
-    needs: [tests]
-    steps:
-    - name: Get Report
-      uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        json-glob: "coverage/coverage-final.json"
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
+
+      - name: Read output variables
+        run: |
+          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
   sonarcloud:
     name: SonarCloud
     needs: [tests]
